/*
 * generated by Xtext 2.30.0.M3
 */
package sqlProgram.services;

import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.List;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Alternatives;
import org.eclipse.xtext.Assignment;
import org.eclipse.xtext.CrossReference;
import org.eclipse.xtext.Grammar;
import org.eclipse.xtext.GrammarUtil;
import org.eclipse.xtext.Group;
import org.eclipse.xtext.Keyword;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.TerminalRule;
import org.eclipse.xtext.common.services.TerminalsGrammarAccess;
import org.eclipse.xtext.service.AbstractElementFinder;
import org.eclipse.xtext.service.GrammarProvider;

@Singleton
public class SqlDslGrammarAccess extends AbstractElementFinder.AbstractGrammarElementFinder {
	
	public class SqlProgramElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "sqlProgram.SqlDsl.SqlProgram");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cSqlProgramAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cSqlProgramKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cQueriesKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3_1 = (Keyword)cGroup_3.eContents().get(1);
		private final Assignment cQueriesAssignment_3_2 = (Assignment)cGroup_3.eContents().get(2);
		private final RuleCall cQueriesQueriesParserRuleCall_3_2_0 = (RuleCall)cQueriesAssignment_3_2.eContents().get(0);
		private final Group cGroup_3_3 = (Group)cGroup_3.eContents().get(3);
		private final Keyword cCommaKeyword_3_3_0 = (Keyword)cGroup_3_3.eContents().get(0);
		private final Assignment cQueriesAssignment_3_3_1 = (Assignment)cGroup_3_3.eContents().get(1);
		private final RuleCall cQueriesQueriesParserRuleCall_3_3_1_0 = (RuleCall)cQueriesAssignment_3_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_3_4 = (Keyword)cGroup_3.eContents().get(4);
		private final Keyword cRightCurlyBracketKeyword_4 = (Keyword)cGroup.eContents().get(4);
		
		//SqlProgram returns SqlProgram:
		//    {SqlProgram}
		//    'SqlProgram'
		//    '{'
		//        ('queries' '{' queries+=Queries ( "," queries+=Queries)* '}' )?
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//{SqlProgram}
		//'SqlProgram'
		//'{'
		//    ('queries' '{' queries+=Queries ( "," queries+=Queries)* '}' )?
		//'}'
		public Group getGroup() { return cGroup; }
		
		//{SqlProgram}
		public Action getSqlProgramAction_0() { return cSqlProgramAction_0; }
		
		//'SqlProgram'
		public Keyword getSqlProgramKeyword_1() { return cSqlProgramKeyword_1; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//('queries' '{' queries+=Queries ( "," queries+=Queries)* '}' )?
		public Group getGroup_3() { return cGroup_3; }
		
		//'queries'
		public Keyword getQueriesKeyword_3_0() { return cQueriesKeyword_3_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_3_1() { return cLeftCurlyBracketKeyword_3_1; }
		
		//queries+=Queries
		public Assignment getQueriesAssignment_3_2() { return cQueriesAssignment_3_2; }
		
		//Queries
		public RuleCall getQueriesQueriesParserRuleCall_3_2_0() { return cQueriesQueriesParserRuleCall_3_2_0; }
		
		//( "," queries+=Queries)*
		public Group getGroup_3_3() { return cGroup_3_3; }
		
		//","
		public Keyword getCommaKeyword_3_3_0() { return cCommaKeyword_3_3_0; }
		
		//queries+=Queries
		public Assignment getQueriesAssignment_3_3_1() { return cQueriesAssignment_3_3_1; }
		
		//Queries
		public RuleCall getQueriesQueriesParserRuleCall_3_3_1_0() { return cQueriesQueriesParserRuleCall_3_3_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_3_4() { return cRightCurlyBracketKeyword_3_4; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_4() { return cRightCurlyBracketKeyword_4; }
	}
	public class QueriesElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "sqlProgram.SqlDsl.Queries");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cSelectionParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cCreationParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		private final RuleCall cUpdateParserRuleCall_2 = (RuleCall)cAlternatives.eContents().get(2);
		private final RuleCall cInsertionParserRuleCall_3 = (RuleCall)cAlternatives.eContents().get(3);
		private final RuleCall cDeleteParserRuleCall_4 = (RuleCall)cAlternatives.eContents().get(4);
		
		//Queries returns Queries:
		//    Selection | Creation | Update | Insertion | Delete;
		@Override public ParserRule getRule() { return rule; }
		
		//Selection | Creation | Update | Insertion | Delete
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//Selection
		public RuleCall getSelectionParserRuleCall_0() { return cSelectionParserRuleCall_0; }
		
		//Creation
		public RuleCall getCreationParserRuleCall_1() { return cCreationParserRuleCall_1; }
		
		//Update
		public RuleCall getUpdateParserRuleCall_2() { return cUpdateParserRuleCall_2; }
		
		//Insertion
		public RuleCall getInsertionParserRuleCall_3() { return cInsertionParserRuleCall_3; }
		
		//Delete
		public RuleCall getDeleteParserRuleCall_4() { return cDeleteParserRuleCall_4; }
	}
	public class ObjectsElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "sqlProgram.SqlDsl.Objects");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cTableParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cColumnParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//Objects returns Objects:
		//    Table | Column;
		@Override public ParserRule getRule() { return rule; }
		
		//Table | Column
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//Table
		public RuleCall getTableParserRuleCall_0() { return cTableParserRuleCall_0; }
		
		//Column
		public RuleCall getColumnParserRuleCall_1() { return cColumnParserRuleCall_1; }
	}
	public class SelectionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "sqlProgram.SqlDsl.Selection");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cSelectionAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cSelectionKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cObjectsKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3_1 = (Keyword)cGroup_3.eContents().get(1);
		private final Assignment cObjectsAssignment_3_2 = (Assignment)cGroup_3.eContents().get(2);
		private final RuleCall cObjectsObjectsParserRuleCall_3_2_0 = (RuleCall)cObjectsAssignment_3_2.eContents().get(0);
		private final Group cGroup_3_3 = (Group)cGroup_3.eContents().get(3);
		private final Keyword cCommaKeyword_3_3_0 = (Keyword)cGroup_3_3.eContents().get(0);
		private final Assignment cObjectsAssignment_3_3_1 = (Assignment)cGroup_3_3.eContents().get(1);
		private final RuleCall cObjectsObjectsParserRuleCall_3_3_1_0 = (RuleCall)cObjectsAssignment_3_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_3_4 = (Keyword)cGroup_3.eContents().get(4);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cClausesKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_4_1 = (Keyword)cGroup_4.eContents().get(1);
		private final Assignment cClausesAssignment_4_2 = (Assignment)cGroup_4.eContents().get(2);
		private final RuleCall cClausesClauseParserRuleCall_4_2_0 = (RuleCall)cClausesAssignment_4_2.eContents().get(0);
		private final Group cGroup_4_3 = (Group)cGroup_4.eContents().get(3);
		private final Keyword cCommaKeyword_4_3_0 = (Keyword)cGroup_4_3.eContents().get(0);
		private final Assignment cClausesAssignment_4_3_1 = (Assignment)cGroup_4_3.eContents().get(1);
		private final RuleCall cClausesClauseParserRuleCall_4_3_1_0 = (RuleCall)cClausesAssignment_4_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_4_4 = (Keyword)cGroup_4.eContents().get(4);
		private final Keyword cRightCurlyBracketKeyword_5 = (Keyword)cGroup.eContents().get(5);
		
		//Selection returns Selection:
		//    {Selection}
		//    'Selection'
		//    '{'
		//        ('objects' '{' objects+=Objects ( "," objects+=Objects)* '}' )?
		//        ('clauses' '{' clauses+=Clause ( "," clauses+=Clause)* '}' )?
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//{Selection}
		//'Selection'
		//'{'
		//    ('objects' '{' objects+=Objects ( "," objects+=Objects)* '}' )?
		//    ('clauses' '{' clauses+=Clause ( "," clauses+=Clause)* '}' )?
		//'}'
		public Group getGroup() { return cGroup; }
		
		//{Selection}
		public Action getSelectionAction_0() { return cSelectionAction_0; }
		
		//'Selection'
		public Keyword getSelectionKeyword_1() { return cSelectionKeyword_1; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//('objects' '{' objects+=Objects ( "," objects+=Objects)* '}' )?
		public Group getGroup_3() { return cGroup_3; }
		
		//'objects'
		public Keyword getObjectsKeyword_3_0() { return cObjectsKeyword_3_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_3_1() { return cLeftCurlyBracketKeyword_3_1; }
		
		//objects+=Objects
		public Assignment getObjectsAssignment_3_2() { return cObjectsAssignment_3_2; }
		
		//Objects
		public RuleCall getObjectsObjectsParserRuleCall_3_2_0() { return cObjectsObjectsParserRuleCall_3_2_0; }
		
		//( "," objects+=Objects)*
		public Group getGroup_3_3() { return cGroup_3_3; }
		
		//","
		public Keyword getCommaKeyword_3_3_0() { return cCommaKeyword_3_3_0; }
		
		//objects+=Objects
		public Assignment getObjectsAssignment_3_3_1() { return cObjectsAssignment_3_3_1; }
		
		//Objects
		public RuleCall getObjectsObjectsParserRuleCall_3_3_1_0() { return cObjectsObjectsParserRuleCall_3_3_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_3_4() { return cRightCurlyBracketKeyword_3_4; }
		
		//('clauses' '{' clauses+=Clause ( "," clauses+=Clause)* '}' )?
		public Group getGroup_4() { return cGroup_4; }
		
		//'clauses'
		public Keyword getClausesKeyword_4_0() { return cClausesKeyword_4_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_4_1() { return cLeftCurlyBracketKeyword_4_1; }
		
		//clauses+=Clause
		public Assignment getClausesAssignment_4_2() { return cClausesAssignment_4_2; }
		
		//Clause
		public RuleCall getClausesClauseParserRuleCall_4_2_0() { return cClausesClauseParserRuleCall_4_2_0; }
		
		//( "," clauses+=Clause)*
		public Group getGroup_4_3() { return cGroup_4_3; }
		
		//","
		public Keyword getCommaKeyword_4_3_0() { return cCommaKeyword_4_3_0; }
		
		//clauses+=Clause
		public Assignment getClausesAssignment_4_3_1() { return cClausesAssignment_4_3_1; }
		
		//Clause
		public RuleCall getClausesClauseParserRuleCall_4_3_1_0() { return cClausesClauseParserRuleCall_4_3_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_4_4() { return cRightCurlyBracketKeyword_4_4; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_5() { return cRightCurlyBracketKeyword_5; }
	}
	public class CreationElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "sqlProgram.SqlDsl.Creation");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cCreationAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cCreationKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cTypeKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Assignment cTypeAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final RuleCall cTypeEStringParserRuleCall_3_1_0 = (RuleCall)cTypeAssignment_3_1.eContents().get(0);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cObjectsKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_4_1 = (Keyword)cGroup_4.eContents().get(1);
		private final Assignment cObjectsAssignment_4_2 = (Assignment)cGroup_4.eContents().get(2);
		private final RuleCall cObjectsObjectsParserRuleCall_4_2_0 = (RuleCall)cObjectsAssignment_4_2.eContents().get(0);
		private final Group cGroup_4_3 = (Group)cGroup_4.eContents().get(3);
		private final Keyword cCommaKeyword_4_3_0 = (Keyword)cGroup_4_3.eContents().get(0);
		private final Assignment cObjectsAssignment_4_3_1 = (Assignment)cGroup_4_3.eContents().get(1);
		private final RuleCall cObjectsObjectsParserRuleCall_4_3_1_0 = (RuleCall)cObjectsAssignment_4_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_4_4 = (Keyword)cGroup_4.eContents().get(4);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cConstaintsKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_5_1 = (Keyword)cGroup_5.eContents().get(1);
		private final Assignment cConstaintsAssignment_5_2 = (Assignment)cGroup_5.eContents().get(2);
		private final RuleCall cConstaintsConstaintParserRuleCall_5_2_0 = (RuleCall)cConstaintsAssignment_5_2.eContents().get(0);
		private final Group cGroup_5_3 = (Group)cGroup_5.eContents().get(3);
		private final Keyword cCommaKeyword_5_3_0 = (Keyword)cGroup_5_3.eContents().get(0);
		private final Assignment cConstaintsAssignment_5_3_1 = (Assignment)cGroup_5_3.eContents().get(1);
		private final RuleCall cConstaintsConstaintParserRuleCall_5_3_1_0 = (RuleCall)cConstaintsAssignment_5_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_5_4 = (Keyword)cGroup_5.eContents().get(4);
		private final Keyword cRightCurlyBracketKeyword_6 = (Keyword)cGroup.eContents().get(6);
		
		//Creation returns Creation:
		//    {Creation}
		//    'Creation'
		//    '{'
		//        ('type' type=EString)?
		//        ('objects' '{' objects+=Objects ( "," objects+=Objects)* '}' )?
		//        ('constaints' '{' constaints+=Constaint ( "," constaints+=Constaint)* '}' )?
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//{Creation}
		//'Creation'
		//'{'
		//    ('type' type=EString)?
		//    ('objects' '{' objects+=Objects ( "," objects+=Objects)* '}' )?
		//    ('constaints' '{' constaints+=Constaint ( "," constaints+=Constaint)* '}' )?
		//'}'
		public Group getGroup() { return cGroup; }
		
		//{Creation}
		public Action getCreationAction_0() { return cCreationAction_0; }
		
		//'Creation'
		public Keyword getCreationKeyword_1() { return cCreationKeyword_1; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//('type' type=EString)?
		public Group getGroup_3() { return cGroup_3; }
		
		//'type'
		public Keyword getTypeKeyword_3_0() { return cTypeKeyword_3_0; }
		
		//type=EString
		public Assignment getTypeAssignment_3_1() { return cTypeAssignment_3_1; }
		
		//EString
		public RuleCall getTypeEStringParserRuleCall_3_1_0() { return cTypeEStringParserRuleCall_3_1_0; }
		
		//('objects' '{' objects+=Objects ( "," objects+=Objects)* '}' )?
		public Group getGroup_4() { return cGroup_4; }
		
		//'objects'
		public Keyword getObjectsKeyword_4_0() { return cObjectsKeyword_4_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_4_1() { return cLeftCurlyBracketKeyword_4_1; }
		
		//objects+=Objects
		public Assignment getObjectsAssignment_4_2() { return cObjectsAssignment_4_2; }
		
		//Objects
		public RuleCall getObjectsObjectsParserRuleCall_4_2_0() { return cObjectsObjectsParserRuleCall_4_2_0; }
		
		//( "," objects+=Objects)*
		public Group getGroup_4_3() { return cGroup_4_3; }
		
		//","
		public Keyword getCommaKeyword_4_3_0() { return cCommaKeyword_4_3_0; }
		
		//objects+=Objects
		public Assignment getObjectsAssignment_4_3_1() { return cObjectsAssignment_4_3_1; }
		
		//Objects
		public RuleCall getObjectsObjectsParserRuleCall_4_3_1_0() { return cObjectsObjectsParserRuleCall_4_3_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_4_4() { return cRightCurlyBracketKeyword_4_4; }
		
		//('constaints' '{' constaints+=Constaint ( "," constaints+=Constaint)* '}' )?
		public Group getGroup_5() { return cGroup_5; }
		
		//'constaints'
		public Keyword getConstaintsKeyword_5_0() { return cConstaintsKeyword_5_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_5_1() { return cLeftCurlyBracketKeyword_5_1; }
		
		//constaints+=Constaint
		public Assignment getConstaintsAssignment_5_2() { return cConstaintsAssignment_5_2; }
		
		//Constaint
		public RuleCall getConstaintsConstaintParserRuleCall_5_2_0() { return cConstaintsConstaintParserRuleCall_5_2_0; }
		
		//( "," constaints+=Constaint)*
		public Group getGroup_5_3() { return cGroup_5_3; }
		
		//","
		public Keyword getCommaKeyword_5_3_0() { return cCommaKeyword_5_3_0; }
		
		//constaints+=Constaint
		public Assignment getConstaintsAssignment_5_3_1() { return cConstaintsAssignment_5_3_1; }
		
		//Constaint
		public RuleCall getConstaintsConstaintParserRuleCall_5_3_1_0() { return cConstaintsConstaintParserRuleCall_5_3_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_5_4() { return cRightCurlyBracketKeyword_5_4; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_6() { return cRightCurlyBracketKeyword_6; }
	}
	public class UpdateElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "sqlProgram.SqlDsl.Update");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cUpdateAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cUpdateKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cObjectsKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3_1 = (Keyword)cGroup_3.eContents().get(1);
		private final Assignment cObjectsAssignment_3_2 = (Assignment)cGroup_3.eContents().get(2);
		private final RuleCall cObjectsObjectsParserRuleCall_3_2_0 = (RuleCall)cObjectsAssignment_3_2.eContents().get(0);
		private final Group cGroup_3_3 = (Group)cGroup_3.eContents().get(3);
		private final Keyword cCommaKeyword_3_3_0 = (Keyword)cGroup_3_3.eContents().get(0);
		private final Assignment cObjectsAssignment_3_3_1 = (Assignment)cGroup_3_3.eContents().get(1);
		private final RuleCall cObjectsObjectsParserRuleCall_3_3_1_0 = (RuleCall)cObjectsAssignment_3_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_3_4 = (Keyword)cGroup_3.eContents().get(4);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cClausesKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_4_1 = (Keyword)cGroup_4.eContents().get(1);
		private final Assignment cClausesAssignment_4_2 = (Assignment)cGroup_4.eContents().get(2);
		private final RuleCall cClausesClauseParserRuleCall_4_2_0 = (RuleCall)cClausesAssignment_4_2.eContents().get(0);
		private final Group cGroup_4_3 = (Group)cGroup_4.eContents().get(3);
		private final Keyword cCommaKeyword_4_3_0 = (Keyword)cGroup_4_3.eContents().get(0);
		private final Assignment cClausesAssignment_4_3_1 = (Assignment)cGroup_4_3.eContents().get(1);
		private final RuleCall cClausesClauseParserRuleCall_4_3_1_0 = (RuleCall)cClausesAssignment_4_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_4_4 = (Keyword)cGroup_4.eContents().get(4);
		private final Keyword cRightCurlyBracketKeyword_5 = (Keyword)cGroup.eContents().get(5);
		
		//Update returns Update:
		//    {Update}
		//    'Update'
		//    '{'
		//        ('objects' '{' objects+=Objects ( "," objects+=Objects)* '}' )?
		//        ('clauses' '{' clauses+=Clause ( "," clauses+=Clause)* '}' )?
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//{Update}
		//'Update'
		//'{'
		//    ('objects' '{' objects+=Objects ( "," objects+=Objects)* '}' )?
		//    ('clauses' '{' clauses+=Clause ( "," clauses+=Clause)* '}' )?
		//'}'
		public Group getGroup() { return cGroup; }
		
		//{Update}
		public Action getUpdateAction_0() { return cUpdateAction_0; }
		
		//'Update'
		public Keyword getUpdateKeyword_1() { return cUpdateKeyword_1; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//('objects' '{' objects+=Objects ( "," objects+=Objects)* '}' )?
		public Group getGroup_3() { return cGroup_3; }
		
		//'objects'
		public Keyword getObjectsKeyword_3_0() { return cObjectsKeyword_3_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_3_1() { return cLeftCurlyBracketKeyword_3_1; }
		
		//objects+=Objects
		public Assignment getObjectsAssignment_3_2() { return cObjectsAssignment_3_2; }
		
		//Objects
		public RuleCall getObjectsObjectsParserRuleCall_3_2_0() { return cObjectsObjectsParserRuleCall_3_2_0; }
		
		//( "," objects+=Objects)*
		public Group getGroup_3_3() { return cGroup_3_3; }
		
		//","
		public Keyword getCommaKeyword_3_3_0() { return cCommaKeyword_3_3_0; }
		
		//objects+=Objects
		public Assignment getObjectsAssignment_3_3_1() { return cObjectsAssignment_3_3_1; }
		
		//Objects
		public RuleCall getObjectsObjectsParserRuleCall_3_3_1_0() { return cObjectsObjectsParserRuleCall_3_3_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_3_4() { return cRightCurlyBracketKeyword_3_4; }
		
		//('clauses' '{' clauses+=Clause ( "," clauses+=Clause)* '}' )?
		public Group getGroup_4() { return cGroup_4; }
		
		//'clauses'
		public Keyword getClausesKeyword_4_0() { return cClausesKeyword_4_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_4_1() { return cLeftCurlyBracketKeyword_4_1; }
		
		//clauses+=Clause
		public Assignment getClausesAssignment_4_2() { return cClausesAssignment_4_2; }
		
		//Clause
		public RuleCall getClausesClauseParserRuleCall_4_2_0() { return cClausesClauseParserRuleCall_4_2_0; }
		
		//( "," clauses+=Clause)*
		public Group getGroup_4_3() { return cGroup_4_3; }
		
		//","
		public Keyword getCommaKeyword_4_3_0() { return cCommaKeyword_4_3_0; }
		
		//clauses+=Clause
		public Assignment getClausesAssignment_4_3_1() { return cClausesAssignment_4_3_1; }
		
		//Clause
		public RuleCall getClausesClauseParserRuleCall_4_3_1_0() { return cClausesClauseParserRuleCall_4_3_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_4_4() { return cRightCurlyBracketKeyword_4_4; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_5() { return cRightCurlyBracketKeyword_5; }
	}
	public class InsertionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "sqlProgram.SqlDsl.Insertion");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cInsertionAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cInsertionKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cObjectsKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3_1 = (Keyword)cGroup_3.eContents().get(1);
		private final Assignment cObjectsAssignment_3_2 = (Assignment)cGroup_3.eContents().get(2);
		private final RuleCall cObjectsObjectsParserRuleCall_3_2_0 = (RuleCall)cObjectsAssignment_3_2.eContents().get(0);
		private final Group cGroup_3_3 = (Group)cGroup_3.eContents().get(3);
		private final Keyword cCommaKeyword_3_3_0 = (Keyword)cGroup_3_3.eContents().get(0);
		private final Assignment cObjectsAssignment_3_3_1 = (Assignment)cGroup_3_3.eContents().get(1);
		private final RuleCall cObjectsObjectsParserRuleCall_3_3_1_0 = (RuleCall)cObjectsAssignment_3_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_3_4 = (Keyword)cGroup_3.eContents().get(4);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cValuesKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_4_1 = (Keyword)cGroup_4.eContents().get(1);
		private final Assignment cValuesAssignment_4_2 = (Assignment)cGroup_4.eContents().get(2);
		private final RuleCall cValuesValueParserRuleCall_4_2_0 = (RuleCall)cValuesAssignment_4_2.eContents().get(0);
		private final Group cGroup_4_3 = (Group)cGroup_4.eContents().get(3);
		private final Keyword cCommaKeyword_4_3_0 = (Keyword)cGroup_4_3.eContents().get(0);
		private final Assignment cValuesAssignment_4_3_1 = (Assignment)cGroup_4_3.eContents().get(1);
		private final RuleCall cValuesValueParserRuleCall_4_3_1_0 = (RuleCall)cValuesAssignment_4_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_4_4 = (Keyword)cGroup_4.eContents().get(4);
		private final Keyword cRightCurlyBracketKeyword_5 = (Keyword)cGroup.eContents().get(5);
		
		//Insertion returns Insertion:
		//    {Insertion}
		//    'Insertion'
		//    '{'
		//        ('objects' '{' objects+=Objects ( "," objects+=Objects)* '}' )?
		//        ('values' '{' values+=Value ( "," values+=Value)* '}' )?
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//{Insertion}
		//'Insertion'
		//'{'
		//    ('objects' '{' objects+=Objects ( "," objects+=Objects)* '}' )?
		//    ('values' '{' values+=Value ( "," values+=Value)* '}' )?
		//'}'
		public Group getGroup() { return cGroup; }
		
		//{Insertion}
		public Action getInsertionAction_0() { return cInsertionAction_0; }
		
		//'Insertion'
		public Keyword getInsertionKeyword_1() { return cInsertionKeyword_1; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//('objects' '{' objects+=Objects ( "," objects+=Objects)* '}' )?
		public Group getGroup_3() { return cGroup_3; }
		
		//'objects'
		public Keyword getObjectsKeyword_3_0() { return cObjectsKeyword_3_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_3_1() { return cLeftCurlyBracketKeyword_3_1; }
		
		//objects+=Objects
		public Assignment getObjectsAssignment_3_2() { return cObjectsAssignment_3_2; }
		
		//Objects
		public RuleCall getObjectsObjectsParserRuleCall_3_2_0() { return cObjectsObjectsParserRuleCall_3_2_0; }
		
		//( "," objects+=Objects)*
		public Group getGroup_3_3() { return cGroup_3_3; }
		
		//","
		public Keyword getCommaKeyword_3_3_0() { return cCommaKeyword_3_3_0; }
		
		//objects+=Objects
		public Assignment getObjectsAssignment_3_3_1() { return cObjectsAssignment_3_3_1; }
		
		//Objects
		public RuleCall getObjectsObjectsParserRuleCall_3_3_1_0() { return cObjectsObjectsParserRuleCall_3_3_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_3_4() { return cRightCurlyBracketKeyword_3_4; }
		
		//('values' '{' values+=Value ( "," values+=Value)* '}' )?
		public Group getGroup_4() { return cGroup_4; }
		
		//'values'
		public Keyword getValuesKeyword_4_0() { return cValuesKeyword_4_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_4_1() { return cLeftCurlyBracketKeyword_4_1; }
		
		//values+=Value
		public Assignment getValuesAssignment_4_2() { return cValuesAssignment_4_2; }
		
		//Value
		public RuleCall getValuesValueParserRuleCall_4_2_0() { return cValuesValueParserRuleCall_4_2_0; }
		
		//( "," values+=Value)*
		public Group getGroup_4_3() { return cGroup_4_3; }
		
		//","
		public Keyword getCommaKeyword_4_3_0() { return cCommaKeyword_4_3_0; }
		
		//values+=Value
		public Assignment getValuesAssignment_4_3_1() { return cValuesAssignment_4_3_1; }
		
		//Value
		public RuleCall getValuesValueParserRuleCall_4_3_1_0() { return cValuesValueParserRuleCall_4_3_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_4_4() { return cRightCurlyBracketKeyword_4_4; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_5() { return cRightCurlyBracketKeyword_5; }
	}
	public class DeleteElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "sqlProgram.SqlDsl.Delete");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cDeleteAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cDeleteKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cObjectsKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3_1 = (Keyword)cGroup_3.eContents().get(1);
		private final Assignment cObjectsAssignment_3_2 = (Assignment)cGroup_3.eContents().get(2);
		private final RuleCall cObjectsObjectsParserRuleCall_3_2_0 = (RuleCall)cObjectsAssignment_3_2.eContents().get(0);
		private final Group cGroup_3_3 = (Group)cGroup_3.eContents().get(3);
		private final Keyword cCommaKeyword_3_3_0 = (Keyword)cGroup_3_3.eContents().get(0);
		private final Assignment cObjectsAssignment_3_3_1 = (Assignment)cGroup_3_3.eContents().get(1);
		private final RuleCall cObjectsObjectsParserRuleCall_3_3_1_0 = (RuleCall)cObjectsAssignment_3_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_3_4 = (Keyword)cGroup_3.eContents().get(4);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cClausesKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_4_1 = (Keyword)cGroup_4.eContents().get(1);
		private final Assignment cClausesAssignment_4_2 = (Assignment)cGroup_4.eContents().get(2);
		private final RuleCall cClausesClauseParserRuleCall_4_2_0 = (RuleCall)cClausesAssignment_4_2.eContents().get(0);
		private final Group cGroup_4_3 = (Group)cGroup_4.eContents().get(3);
		private final Keyword cCommaKeyword_4_3_0 = (Keyword)cGroup_4_3.eContents().get(0);
		private final Assignment cClausesAssignment_4_3_1 = (Assignment)cGroup_4_3.eContents().get(1);
		private final RuleCall cClausesClauseParserRuleCall_4_3_1_0 = (RuleCall)cClausesAssignment_4_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_4_4 = (Keyword)cGroup_4.eContents().get(4);
		private final Keyword cRightCurlyBracketKeyword_5 = (Keyword)cGroup.eContents().get(5);
		
		//Delete returns Delete:
		//    {Delete}
		//    'Delete'
		//    '{'
		//        ('objects' '{' objects+=Objects ( "," objects+=Objects)* '}' )?
		//        ('clauses' '{' clauses+=Clause ( "," clauses+=Clause)* '}' )?
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//{Delete}
		//'Delete'
		//'{'
		//    ('objects' '{' objects+=Objects ( "," objects+=Objects)* '}' )?
		//    ('clauses' '{' clauses+=Clause ( "," clauses+=Clause)* '}' )?
		//'}'
		public Group getGroup() { return cGroup; }
		
		//{Delete}
		public Action getDeleteAction_0() { return cDeleteAction_0; }
		
		//'Delete'
		public Keyword getDeleteKeyword_1() { return cDeleteKeyword_1; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//('objects' '{' objects+=Objects ( "," objects+=Objects)* '}' )?
		public Group getGroup_3() { return cGroup_3; }
		
		//'objects'
		public Keyword getObjectsKeyword_3_0() { return cObjectsKeyword_3_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_3_1() { return cLeftCurlyBracketKeyword_3_1; }
		
		//objects+=Objects
		public Assignment getObjectsAssignment_3_2() { return cObjectsAssignment_3_2; }
		
		//Objects
		public RuleCall getObjectsObjectsParserRuleCall_3_2_0() { return cObjectsObjectsParserRuleCall_3_2_0; }
		
		//( "," objects+=Objects)*
		public Group getGroup_3_3() { return cGroup_3_3; }
		
		//","
		public Keyword getCommaKeyword_3_3_0() { return cCommaKeyword_3_3_0; }
		
		//objects+=Objects
		public Assignment getObjectsAssignment_3_3_1() { return cObjectsAssignment_3_3_1; }
		
		//Objects
		public RuleCall getObjectsObjectsParserRuleCall_3_3_1_0() { return cObjectsObjectsParserRuleCall_3_3_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_3_4() { return cRightCurlyBracketKeyword_3_4; }
		
		//('clauses' '{' clauses+=Clause ( "," clauses+=Clause)* '}' )?
		public Group getGroup_4() { return cGroup_4; }
		
		//'clauses'
		public Keyword getClausesKeyword_4_0() { return cClausesKeyword_4_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_4_1() { return cLeftCurlyBracketKeyword_4_1; }
		
		//clauses+=Clause
		public Assignment getClausesAssignment_4_2() { return cClausesAssignment_4_2; }
		
		//Clause
		public RuleCall getClausesClauseParserRuleCall_4_2_0() { return cClausesClauseParserRuleCall_4_2_0; }
		
		//( "," clauses+=Clause)*
		public Group getGroup_4_3() { return cGroup_4_3; }
		
		//","
		public Keyword getCommaKeyword_4_3_0() { return cCommaKeyword_4_3_0; }
		
		//clauses+=Clause
		public Assignment getClausesAssignment_4_3_1() { return cClausesAssignment_4_3_1; }
		
		//Clause
		public RuleCall getClausesClauseParserRuleCall_4_3_1_0() { return cClausesClauseParserRuleCall_4_3_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_4_4() { return cRightCurlyBracketKeyword_4_4; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_5() { return cRightCurlyBracketKeyword_5; }
	}
	public class EStringElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "sqlProgram.SqlDsl.EString");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cSTRINGTerminalRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cIDTerminalRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//EString returns ecore::EString:
		//    STRING | ID;
		@Override public ParserRule getRule() { return rule; }
		
		//STRING | ID
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//STRING
		public RuleCall getSTRINGTerminalRuleCall_0() { return cSTRINGTerminalRuleCall_0; }
		
		//ID
		public RuleCall getIDTerminalRuleCall_1() { return cIDTerminalRuleCall_1; }
	}
	public class TableElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "sqlProgram.SqlDsl.Table");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cTableAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cTableKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameEStringParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cColumnsKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_4_1 = (Keyword)cGroup_4.eContents().get(1);
		private final Assignment cColumnsAssignment_4_2 = (Assignment)cGroup_4.eContents().get(2);
		private final RuleCall cColumnsColumnParserRuleCall_4_2_0 = (RuleCall)cColumnsAssignment_4_2.eContents().get(0);
		private final Group cGroup_4_3 = (Group)cGroup_4.eContents().get(3);
		private final Keyword cCommaKeyword_4_3_0 = (Keyword)cGroup_4_3.eContents().get(0);
		private final Assignment cColumnsAssignment_4_3_1 = (Assignment)cGroup_4_3.eContents().get(1);
		private final RuleCall cColumnsColumnParserRuleCall_4_3_1_0 = (RuleCall)cColumnsAssignment_4_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_4_4 = (Keyword)cGroup_4.eContents().get(4);
		private final Keyword cRightCurlyBracketKeyword_5 = (Keyword)cGroup.eContents().get(5);
		
		//Table returns Table:
		//    {Table}
		//    'Table'
		//    name=EString
		//    '{'
		//        ('columns' '{' columns+=Column ( "," columns+=Column)* '}' )?
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//{Table}
		//'Table'
		//name=EString
		//'{'
		//    ('columns' '{' columns+=Column ( "," columns+=Column)* '}' )?
		//'}'
		public Group getGroup() { return cGroup; }
		
		//{Table}
		public Action getTableAction_0() { return cTableAction_0; }
		
		//'Table'
		public Keyword getTableKeyword_1() { return cTableKeyword_1; }
		
		//name=EString
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_2_0() { return cNameEStringParserRuleCall_2_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }
		
		//('columns' '{' columns+=Column ( "," columns+=Column)* '}' )?
		public Group getGroup_4() { return cGroup_4; }
		
		//'columns'
		public Keyword getColumnsKeyword_4_0() { return cColumnsKeyword_4_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_4_1() { return cLeftCurlyBracketKeyword_4_1; }
		
		//columns+=Column
		public Assignment getColumnsAssignment_4_2() { return cColumnsAssignment_4_2; }
		
		//Column
		public RuleCall getColumnsColumnParserRuleCall_4_2_0() { return cColumnsColumnParserRuleCall_4_2_0; }
		
		//( "," columns+=Column)*
		public Group getGroup_4_3() { return cGroup_4_3; }
		
		//","
		public Keyword getCommaKeyword_4_3_0() { return cCommaKeyword_4_3_0; }
		
		//columns+=Column
		public Assignment getColumnsAssignment_4_3_1() { return cColumnsAssignment_4_3_1; }
		
		//Column
		public RuleCall getColumnsColumnParserRuleCall_4_3_1_0() { return cColumnsColumnParserRuleCall_4_3_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_4_4() { return cRightCurlyBracketKeyword_4_4; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_5() { return cRightCurlyBracketKeyword_5; }
	}
	public class ColumnElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "sqlProgram.SqlDsl.Column");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cColumnAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cColumnKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameEStringParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cTypeKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cTypeAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final CrossReference cTypeTypeCrossReference_4_1_0 = (CrossReference)cTypeAssignment_4_1.eContents().get(0);
		private final RuleCall cTypeTypeEStringParserRuleCall_4_1_0_1 = (RuleCall)cTypeTypeCrossReference_4_1_0.eContents().get(1);
		private final Keyword cRightCurlyBracketKeyword_5 = (Keyword)cGroup.eContents().get(5);
		
		//Column returns Column:
		//    {Column}
		//    'Column'
		//    name=EString
		//    '{'
		//        ('type' type=[Type|EString])?
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//{Column}
		//'Column'
		//name=EString
		//'{'
		//    ('type' type=[Type|EString])?
		//'}'
		public Group getGroup() { return cGroup; }
		
		//{Column}
		public Action getColumnAction_0() { return cColumnAction_0; }
		
		//'Column'
		public Keyword getColumnKeyword_1() { return cColumnKeyword_1; }
		
		//name=EString
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_2_0() { return cNameEStringParserRuleCall_2_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }
		
		//('type' type=[Type|EString])?
		public Group getGroup_4() { return cGroup_4; }
		
		//'type'
		public Keyword getTypeKeyword_4_0() { return cTypeKeyword_4_0; }
		
		//type=[Type|EString]
		public Assignment getTypeAssignment_4_1() { return cTypeAssignment_4_1; }
		
		//[Type|EString]
		public CrossReference getTypeTypeCrossReference_4_1_0() { return cTypeTypeCrossReference_4_1_0; }
		
		//EString
		public RuleCall getTypeTypeEStringParserRuleCall_4_1_0_1() { return cTypeTypeEStringParserRuleCall_4_1_0_1; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_5() { return cRightCurlyBracketKeyword_5; }
	}
	public class TypeElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "sqlProgram.SqlDsl.Type");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cTypeAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cTypeKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameEStringParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		
		//Type returns Type:
		//    {Type}
		//    'Type'
		//    name=EString;
		@Override public ParserRule getRule() { return rule; }
		
		//{Type}
		//'Type'
		//name=EString
		public Group getGroup() { return cGroup; }
		
		//{Type}
		public Action getTypeAction_0() { return cTypeAction_0; }
		
		//'Type'
		public Keyword getTypeKeyword_1() { return cTypeKeyword_1; }
		
		//name=EString
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_2_0() { return cNameEStringParserRuleCall_2_0; }
	}
	public class ClauseElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "sqlProgram.SqlDsl.Clause");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cClauseKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameEStringParserRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cBodyKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cBodyAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cBodyEStringParserRuleCall_4_0 = (RuleCall)cBodyAssignment_4.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_5 = (Keyword)cGroup.eContents().get(5);
		
		//Clause returns Clause:
		//    'Clause'
		//    name=EString
		//    '{'
		//        'body' body=EString
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//'Clause'
		//name=EString
		//'{'
		//    'body' body=EString
		//'}'
		public Group getGroup() { return cGroup; }
		
		//'Clause'
		public Keyword getClauseKeyword_0() { return cClauseKeyword_0; }
		
		//name=EString
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_1_0() { return cNameEStringParserRuleCall_1_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//'body'
		public Keyword getBodyKeyword_3() { return cBodyKeyword_3; }
		
		//body=EString
		public Assignment getBodyAssignment_4() { return cBodyAssignment_4; }
		
		//EString
		public RuleCall getBodyEStringParserRuleCall_4_0() { return cBodyEStringParserRuleCall_4_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_5() { return cRightCurlyBracketKeyword_5; }
	}
	public class ConstaintElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "sqlProgram.SqlDsl.Constaint");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cConstaintKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cBodyKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cBodyAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cBodyEStringParserRuleCall_3_0 = (RuleCall)cBodyAssignment_3.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_4 = (Keyword)cGroup.eContents().get(4);
		
		//Constaint returns Constaint:
		//    'Constaint'
		//    '{'
		//        'body' body=EString
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//'Constaint'
		//'{'
		//    'body' body=EString
		//'}'
		public Group getGroup() { return cGroup; }
		
		//'Constaint'
		public Keyword getConstaintKeyword_0() { return cConstaintKeyword_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_1() { return cLeftCurlyBracketKeyword_1; }
		
		//'body'
		public Keyword getBodyKeyword_2() { return cBodyKeyword_2; }
		
		//body=EString
		public Assignment getBodyAssignment_3() { return cBodyAssignment_3; }
		
		//EString
		public RuleCall getBodyEStringParserRuleCall_3_0() { return cBodyEStringParserRuleCall_3_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_4() { return cRightCurlyBracketKeyword_4; }
	}
	public class ValueElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "sqlProgram.SqlDsl.Value");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cValueAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cValueKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cColumnvaluesKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3_1 = (Keyword)cGroup_3.eContents().get(1);
		private final Assignment cColumnvaluesAssignment_3_2 = (Assignment)cGroup_3.eContents().get(2);
		private final RuleCall cColumnvaluesColumnValueParserRuleCall_3_2_0 = (RuleCall)cColumnvaluesAssignment_3_2.eContents().get(0);
		private final Group cGroup_3_3 = (Group)cGroup_3.eContents().get(3);
		private final Keyword cCommaKeyword_3_3_0 = (Keyword)cGroup_3_3.eContents().get(0);
		private final Assignment cColumnvaluesAssignment_3_3_1 = (Assignment)cGroup_3_3.eContents().get(1);
		private final RuleCall cColumnvaluesColumnValueParserRuleCall_3_3_1_0 = (RuleCall)cColumnvaluesAssignment_3_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_3_4 = (Keyword)cGroup_3.eContents().get(4);
		private final Keyword cRightCurlyBracketKeyword_4 = (Keyword)cGroup.eContents().get(4);
		
		//Value returns Value:
		//    {Value}
		//    'Value'
		//    '{'
		//        ('columnvalues' '{' columnvalues+=ColumnValue ( "," columnvalues+=ColumnValue)* '}' )?
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//{Value}
		//'Value'
		//'{'
		//    ('columnvalues' '{' columnvalues+=ColumnValue ( "," columnvalues+=ColumnValue)* '}' )?
		//'}'
		public Group getGroup() { return cGroup; }
		
		//{Value}
		public Action getValueAction_0() { return cValueAction_0; }
		
		//'Value'
		public Keyword getValueKeyword_1() { return cValueKeyword_1; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//('columnvalues' '{' columnvalues+=ColumnValue ( "," columnvalues+=ColumnValue)* '}' )?
		public Group getGroup_3() { return cGroup_3; }
		
		//'columnvalues'
		public Keyword getColumnvaluesKeyword_3_0() { return cColumnvaluesKeyword_3_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_3_1() { return cLeftCurlyBracketKeyword_3_1; }
		
		//columnvalues+=ColumnValue
		public Assignment getColumnvaluesAssignment_3_2() { return cColumnvaluesAssignment_3_2; }
		
		//ColumnValue
		public RuleCall getColumnvaluesColumnValueParserRuleCall_3_2_0() { return cColumnvaluesColumnValueParserRuleCall_3_2_0; }
		
		//( "," columnvalues+=ColumnValue)*
		public Group getGroup_3_3() { return cGroup_3_3; }
		
		//","
		public Keyword getCommaKeyword_3_3_0() { return cCommaKeyword_3_3_0; }
		
		//columnvalues+=ColumnValue
		public Assignment getColumnvaluesAssignment_3_3_1() { return cColumnvaluesAssignment_3_3_1; }
		
		//ColumnValue
		public RuleCall getColumnvaluesColumnValueParserRuleCall_3_3_1_0() { return cColumnvaluesColumnValueParserRuleCall_3_3_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_3_4() { return cRightCurlyBracketKeyword_3_4; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_4() { return cRightCurlyBracketKeyword_4; }
	}
	public class ColumnValueElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "sqlProgram.SqlDsl.ColumnValue");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cColumnValueAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cColumnValueKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cValueKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Assignment cValueAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final RuleCall cValueEStringParserRuleCall_3_1_0 = (RuleCall)cValueAssignment_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_4 = (Keyword)cGroup.eContents().get(4);
		
		//ColumnValue returns ColumnValue:
		//    {ColumnValue}
		//    'ColumnValue'
		//    '{'
		//        ('value' value=EString)?
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//{ColumnValue}
		//'ColumnValue'
		//'{'
		//    ('value' value=EString)?
		//'}'
		public Group getGroup() { return cGroup; }
		
		//{ColumnValue}
		public Action getColumnValueAction_0() { return cColumnValueAction_0; }
		
		//'ColumnValue'
		public Keyword getColumnValueKeyword_1() { return cColumnValueKeyword_1; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//('value' value=EString)?
		public Group getGroup_3() { return cGroup_3; }
		
		//'value'
		public Keyword getValueKeyword_3_0() { return cValueKeyword_3_0; }
		
		//value=EString
		public Assignment getValueAssignment_3_1() { return cValueAssignment_3_1; }
		
		//EString
		public RuleCall getValueEStringParserRuleCall_3_1_0() { return cValueEStringParserRuleCall_3_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_4() { return cRightCurlyBracketKeyword_4; }
	}
	
	
	private final SqlProgramElements pSqlProgram;
	private final QueriesElements pQueries;
	private final ObjectsElements pObjects;
	private final SelectionElements pSelection;
	private final CreationElements pCreation;
	private final UpdateElements pUpdate;
	private final InsertionElements pInsertion;
	private final DeleteElements pDelete;
	private final EStringElements pEString;
	private final TableElements pTable;
	private final ColumnElements pColumn;
	private final TypeElements pType;
	private final ClauseElements pClause;
	private final ConstaintElements pConstaint;
	private final ValueElements pValue;
	private final ColumnValueElements pColumnValue;
	
	private final Grammar grammar;
	
	private final TerminalsGrammarAccess gaTerminals;

	@Inject
	public SqlDslGrammarAccess(GrammarProvider grammarProvider,
			TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
		this.pSqlProgram = new SqlProgramElements();
		this.pQueries = new QueriesElements();
		this.pObjects = new ObjectsElements();
		this.pSelection = new SelectionElements();
		this.pCreation = new CreationElements();
		this.pUpdate = new UpdateElements();
		this.pInsertion = new InsertionElements();
		this.pDelete = new DeleteElements();
		this.pEString = new EStringElements();
		this.pTable = new TableElements();
		this.pColumn = new ColumnElements();
		this.pType = new TypeElements();
		this.pClause = new ClauseElements();
		this.pConstaint = new ConstaintElements();
		this.pValue = new ValueElements();
		this.pColumnValue = new ColumnValueElements();
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("sqlProgram.SqlDsl".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	@Override
	public Grammar getGrammar() {
		return grammar;
	}
	
	
	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//SqlProgram returns SqlProgram:
	//    {SqlProgram}
	//    'SqlProgram'
	//    '{'
	//        ('queries' '{' queries+=Queries ( "," queries+=Queries)* '}' )?
	//    '}';
	public SqlProgramElements getSqlProgramAccess() {
		return pSqlProgram;
	}
	
	public ParserRule getSqlProgramRule() {
		return getSqlProgramAccess().getRule();
	}
	
	//Queries returns Queries:
	//    Selection | Creation | Update | Insertion | Delete;
	public QueriesElements getQueriesAccess() {
		return pQueries;
	}
	
	public ParserRule getQueriesRule() {
		return getQueriesAccess().getRule();
	}
	
	//Objects returns Objects:
	//    Table | Column;
	public ObjectsElements getObjectsAccess() {
		return pObjects;
	}
	
	public ParserRule getObjectsRule() {
		return getObjectsAccess().getRule();
	}
	
	//Selection returns Selection:
	//    {Selection}
	//    'Selection'
	//    '{'
	//        ('objects' '{' objects+=Objects ( "," objects+=Objects)* '}' )?
	//        ('clauses' '{' clauses+=Clause ( "," clauses+=Clause)* '}' )?
	//    '}';
	public SelectionElements getSelectionAccess() {
		return pSelection;
	}
	
	public ParserRule getSelectionRule() {
		return getSelectionAccess().getRule();
	}
	
	//Creation returns Creation:
	//    {Creation}
	//    'Creation'
	//    '{'
	//        ('type' type=EString)?
	//        ('objects' '{' objects+=Objects ( "," objects+=Objects)* '}' )?
	//        ('constaints' '{' constaints+=Constaint ( "," constaints+=Constaint)* '}' )?
	//    '}';
	public CreationElements getCreationAccess() {
		return pCreation;
	}
	
	public ParserRule getCreationRule() {
		return getCreationAccess().getRule();
	}
	
	//Update returns Update:
	//    {Update}
	//    'Update'
	//    '{'
	//        ('objects' '{' objects+=Objects ( "," objects+=Objects)* '}' )?
	//        ('clauses' '{' clauses+=Clause ( "," clauses+=Clause)* '}' )?
	//    '}';
	public UpdateElements getUpdateAccess() {
		return pUpdate;
	}
	
	public ParserRule getUpdateRule() {
		return getUpdateAccess().getRule();
	}
	
	//Insertion returns Insertion:
	//    {Insertion}
	//    'Insertion'
	//    '{'
	//        ('objects' '{' objects+=Objects ( "," objects+=Objects)* '}' )?
	//        ('values' '{' values+=Value ( "," values+=Value)* '}' )?
	//    '}';
	public InsertionElements getInsertionAccess() {
		return pInsertion;
	}
	
	public ParserRule getInsertionRule() {
		return getInsertionAccess().getRule();
	}
	
	//Delete returns Delete:
	//    {Delete}
	//    'Delete'
	//    '{'
	//        ('objects' '{' objects+=Objects ( "," objects+=Objects)* '}' )?
	//        ('clauses' '{' clauses+=Clause ( "," clauses+=Clause)* '}' )?
	//    '}';
	public DeleteElements getDeleteAccess() {
		return pDelete;
	}
	
	public ParserRule getDeleteRule() {
		return getDeleteAccess().getRule();
	}
	
	//EString returns ecore::EString:
	//    STRING | ID;
	public EStringElements getEStringAccess() {
		return pEString;
	}
	
	public ParserRule getEStringRule() {
		return getEStringAccess().getRule();
	}
	
	//Table returns Table:
	//    {Table}
	//    'Table'
	//    name=EString
	//    '{'
	//        ('columns' '{' columns+=Column ( "," columns+=Column)* '}' )?
	//    '}';
	public TableElements getTableAccess() {
		return pTable;
	}
	
	public ParserRule getTableRule() {
		return getTableAccess().getRule();
	}
	
	//Column returns Column:
	//    {Column}
	//    'Column'
	//    name=EString
	//    '{'
	//        ('type' type=[Type|EString])?
	//    '}';
	public ColumnElements getColumnAccess() {
		return pColumn;
	}
	
	public ParserRule getColumnRule() {
		return getColumnAccess().getRule();
	}
	
	//Type returns Type:
	//    {Type}
	//    'Type'
	//    name=EString;
	public TypeElements getTypeAccess() {
		return pType;
	}
	
	public ParserRule getTypeRule() {
		return getTypeAccess().getRule();
	}
	
	//Clause returns Clause:
	//    'Clause'
	//    name=EString
	//    '{'
	//        'body' body=EString
	//    '}';
	public ClauseElements getClauseAccess() {
		return pClause;
	}
	
	public ParserRule getClauseRule() {
		return getClauseAccess().getRule();
	}
	
	//Constaint returns Constaint:
	//    'Constaint'
	//    '{'
	//        'body' body=EString
	//    '}';
	public ConstaintElements getConstaintAccess() {
		return pConstaint;
	}
	
	public ParserRule getConstaintRule() {
		return getConstaintAccess().getRule();
	}
	
	//Value returns Value:
	//    {Value}
	//    'Value'
	//    '{'
	//        ('columnvalues' '{' columnvalues+=ColumnValue ( "," columnvalues+=ColumnValue)* '}' )?
	//    '}';
	public ValueElements getValueAccess() {
		return pValue;
	}
	
	public ParserRule getValueRule() {
		return getValueAccess().getRule();
	}
	
	//ColumnValue returns ColumnValue:
	//    {ColumnValue}
	//    'ColumnValue'
	//    '{'
	//        ('value' value=EString)?
	//    '}';
	public ColumnValueElements getColumnValueAccess() {
		return pColumnValue;
	}
	
	public ParserRule getColumnValueRule() {
		return getColumnValueAccess().getRule();
	}
	
	//terminal ID: '^'?('a'..'z'|'A'..'Z'|'_') ('a'..'z'|'A'..'Z'|'_'|'0'..'9')*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	}
	
	//terminal INT returns ecore::EInt: ('0'..'9')+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	}
	
	//terminal STRING:
	//            '"' ( '\\' . /* 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' */ | !('\\'|'"') )* '"' |
	//            "'" ( '\\' . /* 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' */ | !('\\'|"'") )* "'"
	//        ;
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	}
	
	//terminal ML_COMMENT : '/*' -> '*/';
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	}
	
	//terminal SL_COMMENT : '//' !('\n'|'\r')* ('\r'? '\n')?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	}
	
	//terminal WS         : (' '|'\t'|'\r'|'\n')+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	}
	
	//terminal ANY_OTHER: .;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	}
}
