<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="sqlProgram" nsURI="http://www.example.org/sqlProgram" nsPrefix="sqlProgram">
  <eClassifiers xsi:type="ecore:EClass" name="SqlProgram">
    <eStructuralFeatures xsi:type="ecore:EReference" name="queries" upperBound="-1"
        eType="#//Queries" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Queries" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="objects" upperBound="-1"
        eType="#//Objects" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Selection" eSuperTypes="#//Queries">
    <eStructuralFeatures xsi:type="ecore:EReference" name="clause" upperBound="-1"
        eType="#//Clause" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Objects" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Table" eSuperTypes="#//Objects">
    <eStructuralFeatures xsi:type="ecore:EReference" name="column" upperBound="-1"
        eType="#//Column" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Column" eSuperTypes="#//Objects">
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="#//Type"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Type">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Library">
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" upperBound="-1" eType="#//Type"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Clause">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="body" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
