/*
 * generated by Xtext 2.30.0.M3
 */
package sqlProgram.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractSqlDslScopeProvider extends DelegatingScopeProvider {
}
