/*
 * generated by Xtext 2.30.0.M3
 */
package sqlProgram;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class SqlDslRuntimeModule extends AbstractSqlDslRuntimeModule {
}
