/*
 * generated by Xtext 2.30.0.M3
 */
package sqlProgram.serializer;

import com.google.inject.Inject;
import java.util.Set;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Parameter;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.serializer.ISerializationContext;
import org.eclipse.xtext.serializer.acceptor.SequenceFeeder;
import org.eclipse.xtext.serializer.sequencer.AbstractDelegatingSemanticSequencer;
import org.eclipse.xtext.serializer.sequencer.ITransientValueService.ValueTransient;
import sqlProgram.Clause;
import sqlProgram.Column;
import sqlProgram.ColumnValue;
import sqlProgram.Constaint;
import sqlProgram.Creation;
import sqlProgram.Delete;
import sqlProgram.Insertion;
import sqlProgram.QuickSelection;
import sqlProgram.Selection;
import sqlProgram.SqlProgram;
import sqlProgram.SqlProgramPackage;
import sqlProgram.Table;
import sqlProgram.Update;
import sqlProgram.Value;
import sqlProgram.services.SqlDslGrammarAccess;

@SuppressWarnings("all")
public class SqlDslSemanticSequencer extends AbstractDelegatingSemanticSequencer {

	@Inject
	private SqlDslGrammarAccess grammarAccess;
	
	@Override
	public void sequence(ISerializationContext context, EObject semanticObject) {
		EPackage epackage = semanticObject.eClass().getEPackage();
		ParserRule rule = context.getParserRule();
		Action action = context.getAssignedAction();
		Set<Parameter> parameters = context.getEnabledBooleanParameters();
		if (epackage == SqlProgramPackage.eINSTANCE)
			switch (semanticObject.eClass().getClassifierID()) {
			case SqlProgramPackage.CLAUSE:
				sequence_Clause(context, (Clause) semanticObject); 
				return; 
			case SqlProgramPackage.COLUMN:
				if (rule == grammarAccess.getColumnOnCreationRule()) {
					sequence_ColumnOnCreation(context, (Column) semanticObject); 
					return; 
				}
				else if (rule == grammarAccess.getObjectsRule()
						|| rule == grammarAccess.getColumnRule()) {
					sequence_Column(context, (Column) semanticObject); 
					return; 
				}
				else break;
			case SqlProgramPackage.COLUMN_VALUE:
				sequence_ColumnValue(context, (ColumnValue) semanticObject); 
				return; 
			case SqlProgramPackage.CONSTAINT:
				if (rule == grammarAccess.getConstaintOnCreationRule()) {
					sequence_ConstaintOnCreation(context, (Constaint) semanticObject); 
					return; 
				}
				else if (rule == grammarAccess.getConstaintRule()) {
					sequence_Constaint(context, (Constaint) semanticObject); 
					return; 
				}
				else break;
			case SqlProgramPackage.CREATION:
				sequence_Creation(context, (Creation) semanticObject); 
				return; 
			case SqlProgramPackage.DELETE:
				sequence_Delete(context, (Delete) semanticObject); 
				return; 
			case SqlProgramPackage.INSERTION:
				sequence_Insertion(context, (Insertion) semanticObject); 
				return; 
			case SqlProgramPackage.QUICK_SELECTION:
				sequence_QuickSelection(context, (QuickSelection) semanticObject); 
				return; 
			case SqlProgramPackage.SELECTION:
				sequence_Selection(context, (Selection) semanticObject); 
				return; 
			case SqlProgramPackage.SQL_PROGRAM:
				sequence_SqlProgram(context, (SqlProgram) semanticObject); 
				return; 
			case SqlProgramPackage.TABLE:
				if (rule == grammarAccess.getTableOnCreationRule()) {
					sequence_TableOnCreation(context, (Table) semanticObject); 
					return; 
				}
				else if (rule == grammarAccess.getObjectsRule()
						|| rule == grammarAccess.getTableRule()) {
					sequence_Table(context, (Table) semanticObject); 
					return; 
				}
				else break;
			case SqlProgramPackage.UPDATE:
				sequence_Update(context, (Update) semanticObject); 
				return; 
			case SqlProgramPackage.VALUE:
				sequence_Value(context, (Value) semanticObject); 
				return; 
			}
		if (errorAcceptor != null)
			errorAcceptor.accept(diagnosticProvider.createInvalidContextOrTypeDiagnostic(semanticObject, context));
	}
	
	/**
	 * <pre>
	 * Contexts:
	 *     Clause returns Clause
	 *
	 * Constraint:
	 *     (name=EString body=ComplexString)
	 * </pre>
	 */
	protected void sequence_Clause(ISerializationContext context, Clause semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, SqlProgramPackage.Literals.CLAUSE__NAME) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, SqlProgramPackage.Literals.CLAUSE__NAME));
			if (transientValues.isValueTransient(semanticObject, SqlProgramPackage.Literals.CLAUSE__BODY) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, SqlProgramPackage.Literals.CLAUSE__BODY));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getClauseAccess().getNameEStringParserRuleCall_0_0(), semanticObject.getName());
		feeder.accept(grammarAccess.getClauseAccess().getBodyComplexStringParserRuleCall_1_0(), semanticObject.getBody());
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     ColumnOnCreation returns Column
	 *
	 * Constraint:
	 *     (
	 *         name=EString 
	 *         (
	 *             type='int' | 
	 *             type='float' | 
	 *             type='varchar(100)' | 
	 *             type='char(100)' | 
	 *             type='text' | 
	 *             type='date' | 
	 *             type='INT' | 
	 *             type='FLOAT' | 
	 *             type='VARCHAR(100)' | 
	 *             type='CHAR(100)' | 
	 *             type='TEXT' | 
	 *             type='DATE'
	 *         ) 
	 *         constaints+=ConstaintOnCreation?
	 *     )
	 * </pre>
	 */
	protected void sequence_ColumnOnCreation(ISerializationContext context, Column semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     ColumnValue returns ColumnValue
	 *
	 * Constraint:
	 *     value=EString
	 * </pre>
	 */
	protected void sequence_ColumnValue(ISerializationContext context, ColumnValue semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, SqlProgramPackage.Literals.COLUMN_VALUE__VALUE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, SqlProgramPackage.Literals.COLUMN_VALUE__VALUE));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getColumnValueAccess().getValueEStringParserRuleCall_1_0(), semanticObject.getValue());
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Objects returns Column
	 *     Column returns Column
	 *
	 * Constraint:
	 *     name=EString
	 * </pre>
	 */
	protected void sequence_Column(ISerializationContext context, Column semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, SqlProgramPackage.Literals.OBJECTS__NAME) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, SqlProgramPackage.Literals.OBJECTS__NAME));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getColumnAccess().getNameEStringParserRuleCall_1_0(), semanticObject.getName());
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     ConstaintOnCreation returns Constaint
	 *
	 * Constraint:
	 *     body=ComplexString
	 * </pre>
	 */
	protected void sequence_ConstaintOnCreation(ISerializationContext context, Constaint semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, SqlProgramPackage.Literals.CONSTAINT__BODY) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, SqlProgramPackage.Literals.CONSTAINT__BODY));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getConstaintOnCreationAccess().getBodyComplexStringParserRuleCall_0(), semanticObject.getBody());
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Constaint returns Constaint
	 *
	 * Constraint:
	 *     body=ComplexString
	 * </pre>
	 */
	protected void sequence_Constaint(ISerializationContext context, Constaint semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, SqlProgramPackage.Literals.CONSTAINT__BODY) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, SqlProgramPackage.Literals.CONSTAINT__BODY));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getConstaintAccess().getBodyComplexStringParserRuleCall_1_0(), semanticObject.getBody());
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Queries returns Creation
	 *     Creation returns Creation
	 *
	 * Constraint:
	 *     ((type='TABLE' objects+=TableOnCreation (constaints+=Constaint constaints+=Constaint*)?) | (type='INDEX' name=EString? objects+=Table))
	 * </pre>
	 */
	protected void sequence_Creation(ISerializationContext context, Creation semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Queries returns Delete
	 *     Delete returns Delete
	 *
	 * Constraint:
	 *     (objects+=Table (clauses+=Clause clauses+=Clause*)?)
	 * </pre>
	 */
	protected void sequence_Delete(ISerializationContext context, Delete semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Queries returns Insertion
	 *     Insertion returns Insertion
	 *
	 * Constraint:
	 *     (objects+=Table values+=Value values+=Value*)
	 * </pre>
	 */
	protected void sequence_Insertion(ISerializationContext context, Insertion semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Queries returns QuickSelection
	 *     QuickSelection returns QuickSelection
	 *
	 * Constraint:
	 *     (method=EString objects+=Table objects+=Table* clauses+=Clause*)
	 * </pre>
	 */
	protected void sequence_QuickSelection(ISerializationContext context, QuickSelection semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Queries returns Selection
	 *     Selection returns Selection
	 *
	 * Constraint:
	 *     (objects+=Table objects+=Table* clauses+=Clause*)
	 * </pre>
	 */
	protected void sequence_Selection(ISerializationContext context, Selection semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     SqlProgram returns SqlProgram
	 *
	 * Constraint:
	 *     queries+=Queries*
	 * </pre>
	 */
	protected void sequence_SqlProgram(ISerializationContext context, SqlProgram semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     TableOnCreation returns Table
	 *
	 * Constraint:
	 *     (name=EString columns+=ColumnOnCreation columns+=ColumnOnCreation*)
	 * </pre>
	 */
	protected void sequence_TableOnCreation(ISerializationContext context, Table semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Objects returns Table
	 *     Table returns Table
	 *
	 * Constraint:
	 *     (name=EString (columns+=Column columns+=Column*)?)
	 * </pre>
	 */
	protected void sequence_Table(ISerializationContext context, Table semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Queries returns Update
	 *     Update returns Update
	 *
	 * Constraint:
	 *     (objects+=Table clauses+=Clause clauses+=Clause*)
	 * </pre>
	 */
	protected void sequence_Update(ISerializationContext context, Update semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Value returns Value
	 *
	 * Constraint:
	 *     (columnvalues+=ColumnValue columnvalues+=ColumnValue*)?
	 * </pre>
	 */
	protected void sequence_Value(ISerializationContext context, Value semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
}
