/*
 * generated by Xtext 2.30.0.M3
 */
package sqlProgram.ui;

import com.google.inject.Injector;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.osgi.framework.FrameworkUtil;
import sqlProgram.sqldsl.ui.internal.SqldslActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class SqlDslExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FrameworkUtil.getBundle(SqldslActivator.class);
	}
	
	@Override
	protected Injector getInjector() {
		SqldslActivator activator = SqldslActivator.getInstance();
		return activator != null ? activator.getInjector(SqldslActivator.SQLPROGRAM_SQLDSL) : null;
	}

}
