/*
 * generated by Xtext 2.30.0.M3
 */
package sqlProgram.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class SqlDslAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("sqlProgram/parser/antlr/internal/InternalSqlDsl.tokens");
	}
}
